# Generated by Django 5.2.4 on 2025-07-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_landlord_approved_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
